encuesta/apps/preguntas/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.preguntas.views import index, encuesta_view, testview, listar_encuesta, editar_encuesta, eliminar_encuesta, EncuestaList, EncuestaCreate, EncuestaUpdate, EncuestaDelete
app_name ="preguntas"

urlpatterns = [
    url(r'^nuevo$',login_required(EncuestaCreate.as_view()) ,name='formulario'),
    url(r'^error$',testview ,name='error'),
    url(r'^listar$',login_required(EncuestaList.as_view()), name='listar_encuestas'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(EncuestaUpdate.as_view()) ,name='editar_encuestas'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(EncuestaDelete.as_view()) ,name='eliminar_encuestas'),
]

encuesta/apps/usuarios/urls.py
from django.conf.urls import url
from apps.usuarios.views import RegistroUsuario
app_name ="usuarios"

urlpatterns = [
    url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),

]

encuesta/encuesta/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, logout_then_login
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^preguntas/', include ('apps.preguntas.urls', namespace="pregunta")),

    url(r'^usuarios/', include ('apps.usuarios.urls', namespace="usuarios")),

    url(r'^accounts/login/', LoginView.as_view(template_name='index.html'), name="login"),

    url(r'^logout/',logout_then_login, name='logout'),

    path('reset/password_reset', PasswordResetView.as_view(email_template_name="registration/password_reset_email.html"), name = 'password_reset'),

    path('reset/password_reset_done', PasswordResetDoneView.as_view(), name = 'password_reset_done'),

    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),

    path('reset/done',PasswordResetCompleteView.as_view() , name = 'password_reset_complete'),
 
]

encuesta/apps/preguntas/models.py
from django.db import models

# Create your models here.

class Encuesta(models.Model):
    name_user = models.CharField(max_length=20)
    age = models.IntegerField()
    pregunta_1 = models.CharField(max_length=20)
    pregunta_2 = models.CharField(max_length=20)
    pregunta_3 = models.CharField(max_length=20)
    pregunta_4 = models.CharField(max_length=20)
    pregunta_5 = models.CharField(max_length=20)

    def __str__(self):
        return '{}'.format(self.name_user)

encuesta/apps/usuarios/models.py
from django.db import models

# Create your models here.

encuesta/apps/preguntas/forms.py
from django import forms

from apps.preguntas.models import Encuesta

class PreguntasForm(forms.ModelForm):

    class Meta:
        model = Encuesta

        fields=[
            'name_user',
            'age',
            'pregunta_1',
            'pregunta_2',
            'pregunta_3',
            'pregunta_4',
            'pregunta_5',
        ]

        labels={
            'name_user' : 'Nombre', 
            'age' : 'Edad', 
            'pregunta_1' : 'Pregunta #1: Animal preferido.',
            'pregunta_2' : 'Pregunta #2: Comida favorita.',
            'pregunta_3' : 'Pregunta #3: Pais recomendado para visitar.',
            'pregunta_4' : 'Pregunta #4: Coche preferido.',
            'pregunta_5' : 'Pregunta #5: Marca de celulares recomendada.' ,
        }

        widgets ={
            'name_user': forms.TextInput(attrs={'class':'form-control'}),
            'age' : forms.TextInput(attrs={'class':'form-control'}),
            'pregunta_1': forms.TextInput(attrs={'class':'form-control'}),
            'pregunta_2': forms.TextInput(attrs={'class':'form-control'}),
            'pregunta_3': forms.TextInput(attrs={'class':'form-control'}),
            'pregunta_4': forms.TextInput(attrs={'class':'form-control'}),
            'pregunta_5': forms.TextInput(attrs={'class':'form-control'}),
        }

encuesta/apps/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegistroForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

        labels = {
            'username':'Nombre de usuario',
            'first_name' : 'Nombre',
            'last_name':'Apellido',
            'email':'Dirección de correo',
        }

encuesta/apps/preguntas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.preguntas.forms import PreguntasForm
from apps.preguntas.models import Encuesta
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.

def index(request):
    return render(request, 'preguntas/index.html')


def encuesta_view(request):
    if request.method == 'POST':
        form = PreguntasForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('preguntas:listar')
        else:
            return redirect('preguntas:error')
    else:
        form = PreguntasForm()

    return render(request, 'preguntas/preguntas_form.html',{'form':form})


def testview(request):
    return render(request, 'preguntas/prueba_error.html')


def listar_encuesta(request):
    encuestas = Encuesta.objects.all().order_by('id')
    contexto = {'encuestas':encuestas}
    return render(request,'preguntas/encuesta_list.html',contexto)

def editar_encuesta(request, id_encuesta):
    encuesta = Encuesta.objects.get(id=id_encuesta)
    if request.method == 'GET':
        form = PreguntasForm(instance=encuesta)
    else:
        form = PreguntasForm(request.POST, instance=encuesta)
        if form.is_valid():
            form.save()
        return redirect('preguntas:listar_encuestas')
    return render(request, 'preguntas/preguntas_form.html',{'form':form})


def eliminar_encuesta(request, id_encuesta):
    encuesta = Encuesta.objects.get(id=id_encuesta)
    if request.method == 'POST':
        encuesta.delete()
        return redirect('preguntas:listar_encuestas')
    return render(request, 'preguntas/encuesta_delete.html',{'encuesta':encuesta})


class EncuestaList(ListView):
    model = Encuesta
    template_name = 'preguntas/encuesta_list.html'    


class EncuestaCreate(CreateView):
    model = Encuesta
    form_class = PreguntasForm
    template_name = 'preguntas/preguntas_form.html'
    success_url = reverse_lazy('preguntas:listar_encuestas')


class EncuestaUpdate(UpdateView):
    model = Encuesta
    form_class = PreguntasForm
    template_name = 'preguntas/preguntas_form.html'
    success_url = reverse_lazy('preguntas:listar_encuestas')


class EncuestaDelete(DeleteView):
    model = Encuesta
    template_name = 'preguntas/encuesta_delete.html'
    success_url = reverse_lazy('preguntas:listar_encuestas')

encuesta/apps/usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from apps.usuarios.forms import RegistroForm


class RegistroUsuario(CreateView):
    model = User
    template_name = "usuarios/registrar.html"
    form_class = RegistroForm
    success_url = reverse_lazy('preguntas:listar_encuestas')

encuesta/templates/base/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Encuesta De Preferencias {% endblock %}</title>
</head>

<body>
    {% block header %}
    <nav class="navbar navbar-expand-sm  bg-primary navbar-dark justify-content-center">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'preguntas:formulario' %}">Nueva Encuesta</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'preguntas:listar_encuestas' %}">Lista de Encuestas</a>
            </li>
            <li class="nav-item justify-content-right">
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Opciones
                </a>
                <div class="dropdown-menu">
                    <a class="nav-link" href="{% url 'login' %}" style="color: black;">Iniciar Sesión</a>
                    <a class="nav-link" href="{% url 'logout' %}" style="color: black;">Cerrar Sesión</a>
                </div>
            </li>
        </ul>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script>
        function vista() {
            alert('¡SU CUESTIONARIO SE HA GUARDADO CON EXITO!');
        }
    </script>
</body>

</html>

encuesta/templates/index.html
{% extends 'base/base.html' %}

{%block header%}
{% endblock %}

{% block content %}
<div class="container text-center" style="padding-top: 200px; padding-left: 400px;">
    <div class="col-lg-9 col-lg-offset-9">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="username">Nombre de usuario:</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="username">Contraseña:</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <a href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <a href="{% url 'usuarios:registrar' %}">¿No tienes un usuario? Registrese</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Ingresar">
                    </div>
                </div>
            </div>
            {{ form.non_field_errors }}
        </form>
    </div>
</div>
{% endblock %}

encuesta/templates/preguntas/encuesta_delete.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {%csrf_token%}
        <div class="container">
            <h3 style="padding-top: 50px; padding-left: 200px;">¿Desea eliminar el registro de {{object.name_user}}?
            </h3>
            <div class="container" style="padding-top: 50px; padding-left: 200px;" >
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a class="btn btn-primary" href="{% url 'preguntas:listar_encuestas'%}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

encuesta/templates/preguntas/encuesta_list.html
{% extends 'base/base.html' %}

{%block title%}
App Encuesta
{%endblock%}

{% block content %}
<div class="container" style="padding-top: 50px;">
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Nombre del encuestado</td>
                <td>Edad</td>
                <td>Respuesta #1</td>
                <td>Respuesta #2</td>
                <td>Respuesta #3</td>
                <td>Respuesta #4</td>
                <td>Respuesta #5</td>
                <td>Acciones</td>
            </tr>
        </thead>

        <tbody>
            {% if object_list %}
            {% for encuesta in object_list %}
            <tr>
                <td>{{ encuesta.name_user }}</td>
                <td>{{ encuesta.age }}</td>
                <td>{{ encuesta.pregunta_1 }}</td>
                <td>{{ encuesta.pregunta_2 }}</td>
                <td>{{ encuesta.pregunta_3 }}</td>
                <td>{{ encuesta.pregunta_4 }}</td>
                <td>{{ encuesta.pregunta_5 }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'preguntas:editar_encuestas' encuesta.id %}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'preguntas:eliminar_encuestas' encuesta.id %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <h1>NO EXISTEN ENCUESTAS CREADAS</h1>
            {% endif %}
        </tbody>
    </table>
</div>


{%endblock%}

encuesta/templates/preguntas/index.html
{% extends 'base/base.html' %}

{%block title%}
App Encuesta
{%endblock%}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col"></div>
        <div class="col"><h5>Encuesta guardada con exito</h5></div>
        <div class="col"></div>
    </div>
</div>

{%endblock%}

encuesta/templates/preguntas/preguntas_form.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container" style="padding-top: 50px; padding-left: 250px;">
    <div class="abs-center">
        <fieldset class="form-group">
            <legend>
                <h2>Rellene los campos</h2>
            </legend>
            <form method="post">
                {%csrf_token%}
                <!-- {{ form.as_p }} -->
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.name_user.label}}</label>
                            {{form.name_user}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.age.label}}</label>
                            {{form.age}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.pregunta_1.label}}</label>
                            {{form.pregunta_1}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.pregunta_2.label}}</label>
                            {{form.pregunta_2}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.pregunta_3.label}}</label>
                            {{form.pregunta_3}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.pregunta_4.label}}</label>
                            {{form.pregunta_4}}
                        </div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-goup">
                            <label for="">{{form.pregunta_5.label}}</label>
                            {{form.pregunta_5}}
                        </div>
                    </div>
                </div>
                <div class="row" style="padding-top: 20px; padding-left: 15px;">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </fieldset>
    </div>
</div>
{% endblock %}

encuesta/templates/preguntas/prueba_error.html
{% extends 'base/base.html' %}

{%block title%}
App Encuesta
{%endblock%}


{% block content %}
    <div class="container">
        <div class="row justify-content-center">

                <h5 style="padding-top: 10px;">Hubo un problema con su encuesta, intente denuevo</h5>
                <br>
                <br>
        </div>
        <div class="row justify-content-center">
            <img src="https://okdiario.com/img/2018/03/13/como-calcular-porcentaje-de-error-655x368.jpg" >
        </div>
    </div>
{%endblock%}

encuesta/templates/usuarios/registrar.html
{% extends 'base/base.html' %}

{%block header%}
{% endblock %}

{% block content %}
<div class="container" style="padding-top: 50px; padding-left: 250px;">
    <form method="POST">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Nombre</label>
                    <input type="text" class="form-control" name="first_name" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Apellido</label>
                    <input type="text" class="form-control" name="last_name" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Nombre de usuario</label>
                    <input type="text" class="form-control" name="username" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Correo</label>
                    <input type="text" class="form-control" name="email" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Contraseña</label>
                    <input type="password" class="form-control" name="password1" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label>Confirmar contraseña</label>
                    <input type="password" class="form-control" name="password2" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}